### ISSUE TITLE
Incorrect nvidia-cudnn-cu12 in requirements

### ISSUE THREAD

**Issue by SoftologyPro** [JHLew/MoMo#4]
pip install nvidia-cudnn-cu12==8.9.2.26
ERROR: Could not find a version that satisfies the requirement nvidia-cudnn-cu12==8.9.2.26 (from versions: 0.0.1.dev5, 8.9.4.25, 8.9.5.29, 8.9.6.50, 8.9.7.29, 9.0.0.312, 9.1.0.70, 9.1.1.17)
ERROR: No matching distribution found for nvidia-cudnn-cu12==8.9.2.26

**Comment by JHLew** [comment]
Hi, I have updated the `requirements.txt` file with minimal requirements, with other packages to be auto-installed. Would you try out the updated version?

**Comment by SoftologyPro** [comment]
Thank you.
That works now.
