### ISSUE TITLE
How to do more than x2 frames

### ISSUE THREAD

**Issue by SoftologyPro** [JHLew/MoMo#5]
The demo works for x2.
How do we specify 3x, 4x or more if need be?

**Comment by JHLew** [comment]
As mentioned in Issue #1, our project is designed for x2 interpolation.
In case you want to interpolate by higher rates, you can run our interpolation method recurrently,
e.g., x8 interpolation by running our method of x2 three times, which would lead to (((x2) x2) x2) frames of the original video.

**Comment by SoftologyPro** [comment]
OK, thanks for confirming :)
